"""Created friendship

Revision ID: 0e68b4985142
Revises: db15d7052b37
Create Date: 2023-01-09 15:47:47.181803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e68b4985142'
down_revision = 'db15d7052b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frienships',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['chatters.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['chatters.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frienships')
    # ### end Alembic commands ###
