"""Create table app_installations

Revision ID: d8a5153e6de8
Revises: c2d188efd7d5
Create Date: 2023-01-18 17:26:37.314534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a5153e6de8'
down_revision = 'c2d188efd7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_installations',
    sa.Column('chatter_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['chatter_id'], ['chatters.id'], ),
    sa.PrimaryKeyConstraint('chatter_id', 'app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_installations')
    # ### end Alembic commands ###
