"""removed column from game table

Revision ID: db15d7052b37
Revises: 34bd81eaee1f
Create Date: 2023-01-04 15:00:49.657540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db15d7052b37'
down_revision = '34bd81eaee1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
