"""Created conversations

Revision ID: f3b05c9a2d3a
Revises: 0e68b4985142
Create Date: 2023-01-09 16:56:03.339729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b05c9a2d3a'
down_revision = '0e68b4985142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatter_conversation',
    sa.Column('chatter_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatter_id'], ['chatters.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatter_conversation')
    op.drop_table('conversations')
    # ### end Alembic commands ###
